#!/bin/bash

echo -e "\n\e[96m === exit script if anything fails ===\e[0m"
set -e

echo -e "\n\e[96m === cd into Jekyll site directory ===\e[0m"
cd /home/stefan/jekyll/encrateia.informatom.com/

echo -e "\n\e[96m === build Jekyll release ===\e[0m"
jekyll build

echo -e "\n\e[96m === rsync to Server  ===\e[0m"
rsync -vr /home/stefan/jekyll/encrateia.informatom.com/_site/ stefan@mittenin.at:/var/www/encrateia.informatom.com --delete
